#pragma once

#define KUKA_TYPE_COMMAND_EMPTY	0
#define KUKA_TYPE_COMMAND_PARAM	1
#define KUKA_TYPE_COMMAND_BASE	2
#define KUKA_TYPE_COMMAND_TOOL	3
#define KUKA_TYPE_COMMAND_AXACC	4
#define KUKA_TYPE_COMMAND_AXVEL	5
#define KUKA_TYPE_COMMAND_LINAVEXTAXV	6
#define KUKA_TYPE_COMMAND_ONEPOINTMOVEMENT	7

#define KUKA_ONEPOINTMOT_PTP	0
#define KUKA_ONEPOINTMOT_PTP_C_PTP	1
#define KUKA_ONEPOINTMOT_LIN	2
#define KUKA_ONEPOINTMOT_LIN_C_DIS	3
#define KUKA_ONEPOINTMOT_LIN_C_ORI	4
#define KUKA_ONEPOINTMOT_LIN_C_VEL	5

#define KUKA_TYPE_ORI_PTP	0
#define KUKA_TYPE_ORI_CONSTANT	64
#define KUKA_TYPE_ORI_JOINT	128

#define KUKA_TYPE_POINT_AXIS	1
#define KUKA_TYPE_POINT_POS	2

#define KUKA_TYPE_TWOPOINTSMOT_CIRC	0
#define KUKA_TYPE_TWOPOINTSMOT_CIRC_C_DIS	1
#define KUKA_TYPE_TWOPOINTSMOT_CIRC_C_ORI	2
#define KUKA_TYPE_TWOPOINTSMOT_CIRC_C_VEL	3
#define KUKA_TYPE_TWOPOINTSMOT_CIRC_CA	4
#define KUKA_TYPE_TWOPOINTSMOT_CIRC_C_DIS_CA	5
#define KUKA_TYPE_TWOPOINTSMOT_CIRC_C_ORI_CA	6
#define KUKA_TYPE_TWOPOINTSMOT_CIRC_C_VEL_CA	7